#!/bin/bash

print_format () {
    echo "$1"
}

apt_case () {
    PPAS=$(echo $"cat ppas.txt" | tr "\n" " ")

    for ppa in $PPAS
    do
    add-apt-repository ppa:$ppa
    done
}

#Config
print_format $'Select a package manager to use\n\n(1) pamac  (2) apt\n'
read -p ":: Answer: " C; echo

case "$USER" in
"root")
    PFX=""
    ;;
*)
	PFX="sudo"
    ;;
esac

case "$C" in
"1")
    PFX="$PFX pamac install"
    ;;
"2")
	 PFX="$PFX apt install"; apt_case
    ;;
*)
	print_format $'\nNot a valid input.\n' && exit 1
    ;;
esac

#Install and use stow (before applications create config files)
print_format $'First, installing stow...\n'
$PFX stow exa; echo
./stow

#Install apps with selected package manager
print_format $'Installing other applications...\n'
apps=$(cat apps.txt)
$PFX $(echo $apps | tr "\n" " "); echo

#Apps installed through scripts or yay
case "$C" in
"1")
    $PFX yay
    apps=$(cat yay_apps.txt)
    yay -S $(echo $yay_apps | tr "\n" " "); echo
    ;;
"2")
    curl -fsSL https://starship.rs/install.sh | bash 
    mkdir -p ~/.tmp && cd ~/.tmp && git clone git://github.com/wting/autojump.git && cd autojump && ./install.py && rm -rf ~/.tmp/autojump
    ;;
*)
	print_format $'\nNot a valid input.\n' && exit 1
    ;;
esac


#Final config
chsh -s /bin/zsh $USER