#!/bin/zsh
alias swapclean="sudo swapoff -a && sudo swapon -a"
alias ls="exa"
alias ranger=". ranger"
alias cp="cp -i"                                                # Confirm before overwriting something
alias rm="rm -i" #Confirm before deleting
alias df='df -h'                                                # Human-readable sizes
alias free='free -m'                                            # Show sizes in MB
alias sudoe='sudo -E -s' # Keep user's env when using sudo

release=$(cat /etc/*release | grep arch)
if [ -n release ]
then
    alias cat="bat"
fi
